/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonJsInBrowsersIndexRouteImport } from './routes/lesson/js-in-browsers/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonJsInBrowsersIndexRoute = LessonJsInBrowsersIndexRouteImport.update({
  id: '/lesson/js-in-browsers/',
  path: '/lesson/js-in-browsers/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lesson/js-in-browsers': typeof LessonJsInBrowsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson/js-in-browsers': typeof LessonJsInBrowsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lesson/js-in-browsers/': typeof LessonJsInBrowsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lesson/js-in-browsers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lesson/js-in-browsers'
  id: '__root__' | '/' | '/lesson/js-in-browsers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonJsInBrowsersIndexRoute: typeof LessonJsInBrowsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/js-in-browsers/': {
      id: '/lesson/js-in-browsers/'
      path: '/lesson/js-in-browsers'
      fullPath: '/lesson/js-in-browsers'
      preLoaderRoute: typeof LessonJsInBrowsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonJsInBrowsersIndexRoute: LessonJsInBrowsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
